language: python
python:
- '3.6'
install:
- pip install ansible==2.7.1 molecule==2.19.0 apache-libcloud pycrypto
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: FMfpCa0AcPdSvoqMbOlpqsXSfFfLmC7IDsU/C2hiD7Jbr2YWAYy1KLbhcl6o6B11hNKCDbvHN2fn4NequlLQcKsQwX7X0uWpiWEEeUFevH3a6sj/96XdMA1rJfU15u65LdcDO+surpi092J3uYoMmGZ3s6OH53JnDFvLVqfgFH0q4ti/Zm5ZNyYBbxlb3Wka2cB7uC3GCuTx+B8Q+QkhoY4KB43mIc/ejG5PNDJqnUsz+lHCU20oLMoCmUkQ8XQu6KA7Ow9zVGfx/xmJS0m+zUzEpU6Yq9ZQr72RMGUwFEsuel22qfqiYFLwOtEKrO+WdFBSNUo6O7rtUrpTwIfsIgtwuNws0seSma+blleXvPrwwUh89evhjZp+0koGeoi2FEtQfPatUEa0qwI3b/Ij49KKZH+Vei7IOjqXEEQ5MMR3XIt2b5CQXd9JHKKllx/KOVLwz8cBH0aaqIRg4zf8QMRyNEQVas9CNsVZF7JVG5CgTTps5mSiPy1nLpVUI3W+7UfWKLbmdz3B8D5aQXY9sQE1zp6bMgDlgPhRn1W8LiyGhTF6c64VhEsBEUjLKVSJH59u6U3BbsevYWunO4bFZjsQVeo43YpdoU+i7vwbgiZPCD0Pw7nqmd+4hBIPeDoU9/rs0LxevgvBkMEvb83QukQ/sQIJfiFXLFBdPcwLopY=
  - secure: fXo8grUUWHPotrqqL2uSuVkA2S+ZAUG76VnD9rhARSKuoF0sfhudQwdIJyIZH6PFgwsCF9qUcPyJNt7I5KZvN+sJuBfiuENUF+W/ulPdMKMirU4XJlDVS5uxsHnGa8XCFQEIthVlJQ+dj7YVsy/sbytA/p5pJGNyWt+NW9SlNwxXjI93mFBcqeGCFlPa2d3ciwscpnRIruuCwCUduRSOGb96/8Su/ykylN4bGVP001Zx+oCBuhM6KMQ15u6G3AZrpu8EP9BOXA487PDspToKbnblx+JDk2Nh0qQTqYLAR8yJ5Lj8N55d2P1OSpcmFOB4HmO8OrEMNgdZ9nT+jh0Om8WZqTXlSMFocnDFUvPqbJ5bFQMoFzj1UjryNZS7D2jjdzBMErYTWfnsX51Mk1FPa1f2X/FASt6n9ZE1aBPpxjsnaIcWMLMbCcDYfNy6UblFP9LjUFcUe6v0M461kcIgdBW8NSCWFtvk769kKkSF5gxNwWZqikZEJbZvSmjU9xBnEQEw8qvZq04wMItxUQckSpbKF+BCHt5HSrKpZiZiBU+/uqjmm5sbnK6tjo+V9cZAr/vXGiPLTjtNXYJHtbOYpBQLH41l+CCRkwUg/3mM8iZ4PGj2Vxb+Di+X5Buz4HGBGiG/eoRrw+eiaJkr51xe+PYjBFX6bR5v8QZV4gEqfNU=
  - secure: HuoExhlqaDjrXwf/d/+o1H6EiX0BayML/9UQ3qDj5ZC734IWNdY+JAL7RrDeyDzjiqeSi/+zy+Ngk9267oicdYnJFyGmwanK+LVLBhajFpkkEGNxURkZn8/TGn35g6nTQJpEUzfpSnq1ByiGkB4TN0p6xDFAwZe/HlIpf4Ym2eT6mjkMNEJqbLzHmxIgJGGIuUUUc6Xy+htQGhtFRSXUGzB3rEEuBQ1oNKU7BKCL14qwfqVbrSg0rVlXcApvOHsm4dHwlbs12s4bUBM0HCiLr1XBXpyR2t03jhLQyFxdsPztQBKnoTfen4sf+m5LD001HpJBXmJJeHXo2qwOFe5pB0llvEFO7Vxf82hHUbwl1zjTlM78+TTT4MMIYIrtz7Cibtrz5vaaebfwzhP/cSbPI6B2WvXOVSV4tyPAJezbeQNMyr81D1fThgm0WiwMZodyfriGAWhejwYN5a5kYYmosUoeX/xfxs8GF9buovEE9a8YWtd9ksSMy4Glk1yntxVFYCi8nU6+3GJeI8zPgpoS93bkuXl5ZnEtCoUOs4Sk7aTatpL93xF6a9FKFyEIGDsUVXQqK0gHtR17crUtMpSbpFcWXlIhqJICZaSbycExkKDH4ZWORTQN7A4mVSZICM88EctLn/L0LaM10EYG2TcHrQYAAp2TRh7rWy2MyRvVtTo=
before_install:
- openssl aes-256-cbc -K $encrypted_116bbc9c8ed0_key -iv $encrypted_116bbc9c8ed0_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar -xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
- echo $GCE_PROJECT_ID
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
notifications:
  slack:
    rooms:
      secure: qj4HA/A0JF6D/IH3cSc5iy0bNlVikAvlwilMDrJ4jy0yM/9XDk25HSo2MU0WGFU8xtNgW6Z7vy0ONdG8dXAWNLHO1nwKu0ae2h2VuEwJMrIVh1X9ii3apBQpvfz+OABT7sbUUZTqLq1emXn2TMuE7EsubrRqAqSEvGjXsSiocijknNd6YQ6q82/pl8ADHdMu76pfeEEg+iMFO6iSRdW5W42XoP1Yb6wu9TBCPnDqwDs7YByXkfMDn/t1S02y5TpyiPqebQvmdYtwWtGSFVyZwFTaeK5X+qi9Fe/S8vtS3X/B/+8yB9Mc+doLkN7TNXPaOkeCFjufcYWeRVzwcISUsJ7SKP/4oN5CZcFXx2QKRyoZl2EIUq9Q+X9PC6e1Z1bhbkHIr9OE59ycTdn4I3shllAjll4sP5kRl8vDrwp5H3l1hwggpZoMES7q1s1LZ4hzy7WynG5F3dQ5oyaAe2N/69yNROhYz8O25PI0uaQdD42F+xqaFn12LV6QMLGhwor9BdlagPCWlezSzBPfs15y6qdwlpKJvpetaLZ3bVRBm2OA2AYuIV8vpKFS0dLwpvVex0YvQxvDJe6RDFFCwFDt5yscZVpxqE4/cy0iv58m03JkEiSZlT2UW64KvnzHyXTk+aHoqFJgLV+fGd9TinUrEmkkAKx2f7pgDwZbAToL3U8=
