language: python
python:
- '3.6'
install:
- pip install ansible==2.7.1 molecule==2.19.0 apache-libcloud pycrypto
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: GyAfNJBQSUsgalcJcERqPXyAN9cZL+tX9i0Q7Bx3K77ol1uekGaYDfoE9H6JfB492S6oLfYJ0vGZCaN70742jvruDQ+sN4AkER/NbaGXVJ5DPkX9XNTRga8qTJBUmOOzfknest1R+7V1+W93iphIcJvI9BRs4/K7IcdgosupaKPX4z/hV2J1OxdMuxJCJsyACf1ABVoMNIxeg99msaZCLFHh1HHnZAr3QPOoSvfwsa2X6oLJFMQBSZ9xU+IX0pl9qimoz6n23nsKnAeV07a0GrCLcEwRxaV873To43c4dsepBSatFdigANilG7QuJFNfHKagud7NEZ/W8/SBt3kNUX+M6R1kVyl6gvw6OjiPeot2v00kyUn1oZ2IG/lsXxhiewvfDbudAa8CZ380p2YOvt+O1OZpERfUjQjU849EwexNtxSWjYwDepPdCpoTt+Z4XG76+EHYWDUZhTiM0BQNXynbt5EASN4M+85VdLtUBWN70clJJIHYjUMIzTqocezcwE9KNbzblWEloSVVmisfFd+ekIuIcHLFO8/s+kexQdew6nEcEiAt65NRRyOCTMdJbS7PdGOxrSi8DDnTTx++MAAuRk9pEzdaLXAcDZCSvDx+qEUdUatE4y3EEkZ8BvbEZi9qrY3ILM05Jiozfc+0s6IqKl6B0FY16GO3Tv/7xaU=
  - secure: oNn2GTPrNkQR2vi5hGxSTLf3x56SywxDroJWXlzvg5x/YhkdfHZ5JhEvm9DTy0U5DZPpQOLkN2b+ZZ+CrzWVWztzrMZVK3/qI7pTOZH/G2je7rLQijbWQMt4y5pR0uNZNXxwhtQ+RuRRT1FXShqNe+1L4YDL4Ffwtpd+iuB1PWGhrEizsVsTL/zVsS9VoaV50H0jZyAn3Nxt6NpQm6dtVUZDi7FW9j0P8b5SNdOGgcV042HEFvewBGWBMjRCeWg3C5qpemQPcoNYq+BsLybVgekH9aFvMOFvwA5CM+CLqw0sCwq5CjGpEa8ZuLD6DPmWo7oLP/EedEsvQd2rVv+Kx7Rx8hp3zqw99Nszz6F5S6VVnJqGa7dtXJMqqmTKjbmkGvsgSY5RWD1Sa1BC/2g0d9YVcBS8lCj8zzw9mWTS6YcirVQtLC++ayvquTm1C0xNyzZyBVTzIiA+iXvVBpN+tjhfKkbVbNrkXcj3EVcAtE7GGeUEnRQjeuKZAIRYvqCNU3vB6znSb1TI7X2JJw3qLmxSs+EfmNXnE+o9DRrJHRoFPeT0ZP5sFF4it/Ev/leOhtDLpZZuHJbMUWnSiHEDUfr757hTWDOMX9hqj2wgv4KvVdR89P4MB+4Xxg2evmZMd73zZI70u8Z/Z7pMNJ+ZGUt6KOMkJX1XlMfJQ/UN52U=
  - secure: qV/G5sKjw576b4n6rwAXNwFm32WisNmtBILEEdLpgdNKQvVBbbThq+OPawQ51A/8InXWp99SknJeu16d4gd3EvqZx8iYjDK2tcA/+338AvE55KLQAEtiJWCzHklMnPq+x9CzhUTaeahPlLdnkajx+VQiHy3DcKxgFnN9dvEveAL88U3128w+AGeJUDLBOk3GEyYNGnLX+SkrGHQjdFuILg0o1AuyQ+DOaC5axm6m50kclCuDuR5krgmExBOzwJOUr2Qef7N/Chb0vSs5/Z8+aTye4YO2u4XbYy5S9RRKyhdCumCw2m7Ia6Zdr3peZG2IytNgEVHfm6I7CxDHxpPGcvBfDVZehHRrr8TvFIaXJPq4vWwTfKrlg+qHGu7dQ3z4UqflacPQGYbdpI2xAirzelQKadDq9c3pmW6JFQpgUbHdcHplzHUa219kuT0YldyTCdVVH0naMauErhmceXTfPY9txiAPdmFdF9GJdGM+R5zgRiutJKYOqxorhhWwybDPhjFJd2XNAxve1J9XaN1zQlY4l1YxxHH2EeIOKADuFDh1PNECq09+ujU0ciYjssDxLTy4wOvA4E5CHQYpUoiv9U6k0EAknmRQl429Zb9tCzYQH9IVbfK22ASghU96mZC0TP6GYlBO6gatVzkd+fcMJf56L8E6QV0qXGEvZhb8vos=
before_install:
- openssl aes-256-cbc -K $encrypted_116bbc9c8ed0_key -iv $encrypted_116bbc9c8ed0_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar -xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
- echo $GCE_PROJECT_ID
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
notifications:
  slack:
    rooms:
      secure: qj4HA/A0JF6D/IH3cSc5iy0bNlVikAvlwilMDrJ4jy0yM/9XDk25HSo2MU0WGFU8xtNgW6Z7vy0ONdG8dXAWNLHO1nwKu0ae2h2VuEwJMrIVh1X9ii3apBQpvfz+OABT7sbUUZTqLq1emXn2TMuE7EsubrRqAqSEvGjXsSiocijknNd6YQ6q82/pl8ADHdMu76pfeEEg+iMFO6iSRdW5W42XoP1Yb6wu9TBCPnDqwDs7YByXkfMDn/t1S02y5TpyiPqebQvmdYtwWtGSFVyZwFTaeK5X+qi9Fe/S8vtS3X/B/+8yB9Mc+doLkN7TNXPaOkeCFjufcYWeRVzwcISUsJ7SKP/4oN5CZcFXx2QKRyoZl2EIUq9Q+X9PC6e1Z1bhbkHIr9OE59ycTdn4I3shllAjll4sP5kRl8vDrwp5H3l1hwggpZoMES7q1s1LZ4hzy7WynG5F3dQ5oyaAe2N/69yNROhYz8O25PI0uaQdD42F+xqaFn12LV6QMLGhwor9BdlagPCWlezSzBPfs15y6qdwlpKJvpetaLZ3bVRBm2OA2AYuIV8vpKFS0dLwpvVex0YvQxvDJe6RDFFCwFDt5yscZVpxqE4/cy0iv58m03JkEiSZlT2UW64KvnzHyXTk+aHoqFJgLV+fGd9TinUrEmkkAKx2f7pgDwZbAToL3U8=
