language: python
python:
- '3.6'
install:
- pip install ansible==2.7.1 molecule==2.19.0 apache-libcloud pycrypto
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: YOpGSzk7/C8dQAEaC69hkNqV5MmB82m5YtB42PU56Rnn9zCdFGrzaYLMMfdvNAJn5MIoEsDQr05mePqCCCXcAuAL0YEVgPRHlom7sN7y2T+ftd4xOPduDSko+Q8hgvVqjg465fpOJlOcL8YiYRUrCQP9BQXxvd3/ZaxiB8y4hvZ+/5eonFOdeBeB2qqizZ2funEeK9WuCntGFsWwYDufAbY+3ZSlLqaoACK5RAkaF5sNtM1tZXlHTU4jGnA4F1klI+lgvrSFNee7zI1nIwnxVHcZwGjSokYdRHpkKpUZKOOikTmLaf+anCi8JnBuCKbfc2JLAAMwYY8RPkoMOlbglZcA8HDm5+C/mSiTYSJIHAF5p+sJb+Ufk3IRFt3W7kQlkWJ6KKj4a5t9OAK61b+m6gmCsc5Kd6Sef71OksEep5RUXpSdSwFkDJD6sqer6plye+LxJj2Ld/KnkJvXBecM2BFImzy5OsPU0U1fHFslNdjfkoRQjSRD2YLYp+nCaRkyfL84GQklMLhysK7BMDWDwcppxIug3YUJzhkNNMvvKROE5u7fjhVhyTlpIjUd5w86txKfg3C/qRwyh4vRJsPQ2KQm/9b5zUMbpvBmCw3u8Ec63ykA5/RSsbS4Ite9VSQJFoCGeASjkYtEoLSJodMit6eMKru8RlCQpljNpUG5j2w=
  - secure: MiPwbcFUWQ+e1jdO1/yP55wQ9tppSW186g1/MVmEoyQqc7A4q8n9nJyJkRh3QbogvqR5vdIGkE5rp9791dWeDBthi3n3t1JJ4PqsLt4eGCUhBc76D+c6HDt+kd8maj3Ltu7EeS4QZr/Y6fQqY6M/NjGID/V8QshuuHBxXKb23M2LVLSYplw79qaXONJUbuSAyojH7/D5GMCcKacYaEGM6AQSzowvwud4/EsnHYrLBYJ2bJZXq6iZdzHcbUl5dhfE+/1He6yqPVIYQPcV7/8R4VWUE54uutrNPEPGAuzzA6l/JthHKmbl1hr0ZBd9kB4uUh0GJswCD9CS9vRXBVjK475Kq+4gtplXrXwkhbyH6O7aUS+jcxVxEy36Wh+AUjmSYyRoHrYP/eADdkzt4ss47dMJu3t9Xa1WL4NDBoMzj0TKwbEZRt9KaHTtttv4RjH56b0cglbv6/zy6SZcWfG/re+n3pH7bRVWLQ8f7tqfjSvWgAzt+CeioH3CwM+hPM5zkiihuuOZPl2GbC6EoM/1T9Tt29+6J02tSdbua/H3d8zbMLZG8r9EsOKMo3WiebKDjucSg5RrCvhplrHO89tC43VdAn8LySBx0fERWcRGoCcNMffrg6YT5JMf9qxeNWCl67W5s5FJV9Do9SSMOy/563+KqnMk9H1EhTg7TNTppl4=
  - secure: JqSbuFDpUBEMXBpoD7ic+rdQ1kYx94dgfFqcVhoLp8mN8d5KL1fbxMieobGlXWazxHfJX0JestgnI/Wq+OXP3X4rsyrYm26lJ0GYCSrsEsZ01FzJW5hoXYczxTZ9MC5Vsk0anpDV9yoqmI9//kp7SocQ6mbuy+9HOG2mFGD+2DJLW/DQndauxVsvqyVwHYpKHGTAOoLv55SCT7+tvzvnwlRb5+UFnKs4fY2QWX+CHbDhAzl5TyW12B4OKBnlixB2H6nQRNlx98SBcePLXctMXKZWYeadxc522UI4XB3zQ7x7zljv698tb5s13foM3Eq3hGOrFRRJFcIQy/l5VCOM1qVacXVCEK140gTyBSgq2m3d5tPtXJrIy1Uo7pYFeqob4njFD1WxM0L/DgVmaDws7Dj2MjZJ9gl2lXdRKr8BxCgYDQ5enXavYh04d10fPFu5jspMTK6vwoetGjOcUDYu5AjwDRH2dmhvB5g+gZkwiMELHOkoIKjcBB6rP+YMCVQOBVf/Ux6AkFvVzYd+WukmBizD5mxDrcOKSb6JOdZTkyT1bdznQMhpwnFOu0uOLoOWlyDwQcBXTByWGL5Ar1Ii0qw+nTSFbD3ctc8cy+ReaIqdjt29ANycUkqPQKSniEVkrE3Oe0lDHClh9wnccDGbhH8eY499eKIxeHmTTQrFXvY=
before_install:
- openssl aes-256-cbc -K $encrypted_116bbc9c8ed0_key -iv $encrypted_116bbc9c8ed0_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar -xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
- echo $GCE_PROJECT_ID
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
notifications:
  slack:
    rooms:
      secure: qj4HA/A0JF6D/IH3cSc5iy0bNlVikAvlwilMDrJ4jy0yM/9XDk25HSo2MU0WGFU8xtNgW6Z7vy0ONdG8dXAWNLHO1nwKu0ae2h2VuEwJMrIVh1X9ii3apBQpvfz+OABT7sbUUZTqLq1emXn2TMuE7EsubrRqAqSEvGjXsSiocijknNd6YQ6q82/pl8ADHdMu76pfeEEg+iMFO6iSRdW5W42XoP1Yb6wu9TBCPnDqwDs7YByXkfMDn/t1S02y5TpyiPqebQvmdYtwWtGSFVyZwFTaeK5X+qi9Fe/S8vtS3X/B/+8yB9Mc+doLkN7TNXPaOkeCFjufcYWeRVzwcISUsJ7SKP/4oN5CZcFXx2QKRyoZl2EIUq9Q+X9PC6e1Z1bhbkHIr9OE59ycTdn4I3shllAjll4sP5kRl8vDrwp5H3l1hwggpZoMES7q1s1LZ4hzy7WynG5F3dQ5oyaAe2N/69yNROhYz8O25PI0uaQdD42F+xqaFn12LV6QMLGhwor9BdlagPCWlezSzBPfs15y6qdwlpKJvpetaLZ3bVRBm2OA2AYuIV8vpKFS0dLwpvVex0YvQxvDJe6RDFFCwFDt5yscZVpxqE4/cy0iv58m03JkEiSZlT2UW64KvnzHyXTk+aHoqFJgLV+fGd9TinUrEmkkAKx2f7pgDwZbAToL3U8=
