language: python
python:
- '3.6'
install:
- pip install ansible==2.7.1 molecule==2.19.0 apache-libcloud pycrypto
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: graLrQ90puJvczKOzVlMX43LpYz/Glg8jNw4GGxpNJNOEPxzhjtASG6JYcA87uypgYLSBKMbydLKjhnndX4RfQmOl/ySlbaX6whsRa6KZYXml91VjibJcRhOH7IkkSNtwYzwa9TzxKqJWwTVpi9SsVcKyeTodOga3sl5h9dYmpLZV5BTbLD7sjZak8wMVlngvPCJ4p1kIxTY1rzzxl1XlvFa/5ZWrjHLf2W7hYH8DSq5ZpZbya+bPsHgzCm8zPHZtj93NCr6VZVLYa4bOecDtDUt4QaA0SFLP0NmcMC4LL7QySGpsnK1JtmXpFHH3B1fBusyvhldD7UIBvjZL8Ur+yla37ZBwcFAGnv5GYYOnbaG725HXXGXVPlMH+H1pvN4aEyQIvGmnb6BQajJD6RZVd6xbqsA4308fA96DtuYQjw9wABBHCkhXOmDQhmc5BHDOLYKDTRyhWEEEhmI2xCAHafAyzh8ZuYX95h9BB1AI6bufSQFQgdpTJ410zwCcq3+2ioGxJ10uSvC2WRrY7IIMNZ1alaf3LHKBsv6+UEuYJGkw3qSHUpMrEmejUlB3gRoLi6C+lVO3YhmF46E70EXUjsQOgej+XeIet+ffe6sFH5E9mtM9+wVREG+dyAtpBJYr/9fV/lS1C5SXX7OG4jnBb2jEzRfD+0XTO8OPnvc2Gs=
  - secure: qfeuTMeuxkUQIfn1vizQsJCWFneytVxEDs7iBsBCdIqhpyLNrz47PhYGsE389Vt6rbiezqJQvG+sIzoee+y0TQrbAgbaYKPyzjZgPYmTQ/Sgj2V2+TiOaYhjaq5hChF+jJ3uCfKTeFulORYWaMVA1yG3qG4O8zQGTQO3sQADSeq/if+KH6hOmdiKvC42slZQzUQjoLf+9UPiRzRHTjB3YbAGZrzhsn97n5A4k9Ggd2UXBZWHP/LLfd2xB4NpJ8Z5+fzORbclI637PUxkBrWAlmx6XHlU07cZcSMhmkRdY05NNNA1ZxWNjR25bM718vjWXF2WzSoC0kKB5qNnGvBGJ0BRH5kLMfZDUXtUKI0Hc50WOphWFJMnJ4t07v+CSoZY1lEGm2Lak9tbsxDdv0ztN0mCqvt6zsAn4FXz8HZ0PW8fzpEe2IU16FNKSa03SeCXXIrCFF795ewtT6S/YRHm2OqVvAdDnqUefQR/YIXPQF8F7Z8lmnzJVHc71KyMXqB+sH4Fw2IT3vPHy4YdC8RSe3+am/rJTWRBi8GWtOzt6/jw+itnguE0FriX5e+XHyek9Hg7394+UNg6FmSVnkYI9E47Oc+3aDHUjKCCipludYiIzjCQ4uHbCLG7aW2QA+/EkTujSumFumi8h3tUfsKFqU3KLPIa+4SvFoQKPslkWlE=
  - secure: jdNAvJbp5z2CbPSUSpZPV+k0peGoOpvDXyb1OjeliaaNslRsg5pqxZUnPN+itEvhNzLW2bY1mKQiEG+TbruJWGHPyqM339YvFOF3Pstb7znNL97XWhbTigiRW9LVPDShqrKjASkA5GubWIRyRzJF4IofTOcpJOCx1TdYYBZqVakfJdiyf1ajBZJ1WMA+82CW/IMbVS5cjgzunFh9XcE7sXz7WYlI84VzlRosr5ZqNVQVCB+cNSDu2yokSfi+XDsK/UQv31TjgNhJEaIazS6lxgnOz0JIDXY23mis1thLK1nUuUHM6SccYnC9J9hyTov0DdTsBZy+0D2dSEdqcMIeG2Xnj8bRvjXMzTWDEqogMlM3Fru7Hru4kVD0+UX6/6zB+eKpSAyjFASYkui7UnmUjZnyG1VzQ1EpL7svJT+Ie7st39JQVPHd+AbGaL34j5j52RPFBfISTc6Hz4rhkBxS3hk5Vz0gXHqaCkV1EoGA2tEVnyFeqpe1KPxRBdYop/8ETsv3XYWeTTHI+wgeldI828OUMYhX7L2z2uqAfyCaEdXIU2aqfEXblJZhTk+BY6YGWA702JCkXMundAhyAqeqq3e+RokrQIyfraomzJrAulEoxF+185xiASjjNoe+VebhTtgYUMgushfqcrtmiVbf/rXv3lcVeTVwZO6/CWckMnw=
before_install:
- openssl aes-256-cbc -K $encrypted_116bbc9c8ed0_key -iv $encrypted_116bbc9c8ed0_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar -xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
- echo $GCE_PROJECT_ID
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
notifications:
  slack:
    rooms:
      secure: qj4HA/A0JF6D/IH3cSc5iy0bNlVikAvlwilMDrJ4jy0yM/9XDk25HSo2MU0WGFU8xtNgW6Z7vy0ONdG8dXAWNLHO1nwKu0ae2h2VuEwJMrIVh1X9ii3apBQpvfz+OABT7sbUUZTqLq1emXn2TMuE7EsubrRqAqSEvGjXsSiocijknNd6YQ6q82/pl8ADHdMu76pfeEEg+iMFO6iSRdW5W42XoP1Yb6wu9TBCPnDqwDs7YByXkfMDn/t1S02y5TpyiPqebQvmdYtwWtGSFVyZwFTaeK5X+qi9Fe/S8vtS3X/B/+8yB9Mc+doLkN7TNXPaOkeCFjufcYWeRVzwcISUsJ7SKP/4oN5CZcFXx2QKRyoZl2EIUq9Q+X9PC6e1Z1bhbkHIr9OE59ycTdn4I3shllAjll4sP5kRl8vDrwp5H3l1hwggpZoMES7q1s1LZ4hzy7WynG5F3dQ5oyaAe2N/69yNROhYz8O25PI0uaQdD42F+xqaFn12LV6QMLGhwor9BdlagPCWlezSzBPfs15y6qdwlpKJvpetaLZ3bVRBm2OA2AYuIV8vpKFS0dLwpvVex0YvQxvDJe6RDFFCwFDt5yscZVpxqE4/cy0iv58m03JkEiSZlT2UW64KvnzHyXTk+aHoqFJgLV+fGd9TinUrEmkkAKx2f7pgDwZbAToL3U8=
