language: python
python:
- '3.6'
install:
- pip install ansible==2.7.1 molecule==2.19.0 apache-libcloud pycrypto
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: o+GWcC9kAwKuAi2d9PyIH+leNCqd2d2nPQYosDa55Av8nyY9hqSjDn5p0P4fNwfjUGIWTtOvctEA4zxQeSIA3SihHlAtqqqg8nTKQJV6pqauACfPd5rdUyYjLTLP080ZcznXd03zang8CixVeNA3cn0iuaWDHRx/K3t/9DK3ZvvVgTZn8/zLNLk/Mx5DyNfvKASLztmYDNV50OkguinC26FXCVS+hcvk6ae7S/lzkjdRl/nHC4Tt84s6VJbANhIbxEBeC26PC4fSiWACThQKbQTXNigcTinEua4H+rFsfDC/rU/fuqyMFtcbgnlGCXma3xUr7peG72liuBJ3XHTanbCY88smHordGZ3p83J6tFrDu3UiVPzKpNffbFtWGgYS5eQuYH8konrWilGgrjRuL0csbeG8fCLO9acfn5QI4+u6MTB9BRaCIuvqWFYE34Ab4CyFXCGIp13gQjWdhySK7rH9WR+HcNWNk2EJAYKXka/O8tfNCuBFUyYb6avU7tAjmkJnVqatJTbWsvs7+lCYKrnxK7ywS6evRA3ACYPWrjQVvlic5NZxai1qlNR2PidBjuWpYXHRtHOuyE0kG8GUczCUBLWS/qdCH165sPYA52eO3hLo9fApRnshrpgClhrzc4WJtH9u1kJVj+8KJJgZdKTaL4GeuVJmiaS4nz6tS60=
  - secure: Z+RJvnYyBgiyvjV7DF7zWiN1oEZchSceXUiiPAkFONP4PhVaYk/sgzuYjZGZ61gd6j2aB5ZHd6swlLkLcKCbMinu5ipdmez7HUX32zYtgc2S1+aLZjPdvw1XcAo7yjqzNDd16O+p+Ryl9j/OWFIj5lPV0kqyP/VwNkIu1mh1j4QeDUz3bOKrF2xVWSEGDd/88O7MrGJCrY4wde8CZX2ZnSOWiSNUv/eSErU/a2H75A/Q85ZWr7BpjOSdeVAssEAGFjfIWhaHPgxhzs+HnodUr+UNnmnethXnbuMwhmZl7PXFQnsKrHWWn9T03GVsDFrga2IqDhE0Mm9hyWKXWY897pYpxds4eeU6l3wv+eUB8XHTKAKDrOb1XFDPhMMFnodMzXrSn4U8cXyeMbBnFAxQ3rn+FndHVdl/koTHBvzs4qjmEcpZ6QM6nV3xorGY8A+D7BBfNAsmpfxbMOVmzrd017jeBYMFyeXn+wa60gTdf43sCdn38T0iNEgFMzna01QDqXVDREX+dgPGMeaoC9UcELJsaKhl44edrXOmWyGqvhlG/6DbN15o/HTzu72skycguOmyRZZRycviMCDPeNTBG6jeQMmz/PXKp9CnZrFxCe+gV20o9I4JTuCkg/rzz3cB8gNvHMbbF1UFLlQmdvGyqJf1mwb5Mb/hhs7Ssg9pzQ8=
  - secure: jqI0/EcExsx6VsUZ1eslAqxpNjMDqty265FStO2h8fhSj/h3B/VqWvS86HyvZ5sBN2sHO/N2JdpyVlQhqZJc1MogtbMSD2CXTzJx+jYTJ5GUazudM3KVaovdoZcxIiWWvY2cTC1VZtt45S04J8f0m/XPwHbFJGjjksnttuvQvYBV8B3byfw5kuceu+H82PRXs93GaIQ0abt/IiX3RHlcguNMc+AGAHETpC7tUMJaurIz5o3YnaKO5R+tI+quNPbCutk3ldNm7r8SlFoZ/EGvD/cJ5I9lK2YFkqTCnbR5HeiUwYbfpAeWXGxLz25qHx95F6o2fZoVIGUslZJsk7lmOfgF42SZiXroMskki9sQcc7ScKDQsact1R2EtcuPAHXdS0BWAIOy5MTve3ejNieiIfkc5b55h5HLQUAWRupHhAIIFWNbUF3Xc/zClYYzf1zk8ud3su6yArcGo1WBMFTc1YVqaM73zLuh3xheYVW77J0eCHP4BO4fbYP2UhY0I6VizZsAAc8OQDNqqjWacqjlEH/kh8iMBfRpFXjKD6f3nAuKseWI9Qr+Igbp3viD/Jh4DUOoyobGfIgFA8JR+ZLKD9jFW+NfRaVZey/fmcxzZmGg6r5YtunCbrjX5plWqO4Xl0zs3K6H2Y0A7zB6oKs4kZ3Zi772hmH9aqnzeydtJrM=
before_install:
- openssl aes-256-cbc -K $encrypted_116bbc9c8ed0_key -iv $encrypted_116bbc9c8ed0_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar -xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
- echo $GCE_PROJECT_ID
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
notifications:
  slack:
    rooms:
      secure: qj4HA/A0JF6D/IH3cSc5iy0bNlVikAvlwilMDrJ4jy0yM/9XDk25HSo2MU0WGFU8xtNgW6Z7vy0ONdG8dXAWNLHO1nwKu0ae2h2VuEwJMrIVh1X9ii3apBQpvfz+OABT7sbUUZTqLq1emXn2TMuE7EsubrRqAqSEvGjXsSiocijknNd6YQ6q82/pl8ADHdMu76pfeEEg+iMFO6iSRdW5W42XoP1Yb6wu9TBCPnDqwDs7YByXkfMDn/t1S02y5TpyiPqebQvmdYtwWtGSFVyZwFTaeK5X+qi9Fe/S8vtS3X/B/+8yB9Mc+doLkN7TNXPaOkeCFjufcYWeRVzwcISUsJ7SKP/4oN5CZcFXx2QKRyoZl2EIUq9Q+X9PC6e1Z1bhbkHIr9OE59ycTdn4I3shllAjll4sP5kRl8vDrwp5H3l1hwggpZoMES7q1s1LZ4hzy7WynG5F3dQ5oyaAe2N/69yNROhYz8O25PI0uaQdD42F+xqaFn12LV6QMLGhwor9BdlagPCWlezSzBPfs15y6qdwlpKJvpetaLZ3bVRBm2OA2AYuIV8vpKFS0dLwpvVex0YvQxvDJe6RDFFCwFDt5yscZVpxqE4/cy0iv58m03JkEiSZlT2UW64KvnzHyXTk+aHoqFJgLV+fGd9TinUrEmkkAKx2f7pgDwZbAToL3U8=
