language: python
python:
- '3.6'
install:
- pip install ansible==2.7.1 molecule==2.19.0 apache-libcloud pycrypto
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: gtG43CB1S4VhFlKvXIM33LmdFpDQ324NDWqdaScRUcRD03EMHW7VxclHCYVEiaZRgNRcr//VZuVRKdhjqfH+vP6Z7VrsFzMdCDkuQNis52mIiXWynw/M5FjEUI01C8uAcFvIS9FFtCax0lKNCAUsaepKaxI9iLrZj83+ekZkG+a/OfdOevZnkOpHb8RxBbDDfjWC3SJsAIxaQzfiVLBztTK9ehpnVu64DseB8TQZd1A+I8IRKCat1P4RsqHOgh8OLArFdcsraxKZ+HTLfTgutAHENj6bBWnR+VgsIcxtMzcrKFGdJv2442B05NK+2dDVEJY6V3WNC9u21QywKr18/DZCAFvVWCiKMTlO9LynEWnaWjStBcOuM1zxW4UypcTV0Kf4QO9FPoWv5Wmr8spK9R1v+DfvBqrYmYGVfyYLIxJ9TqbPS5btJtLjthKNA/eamObIdepdAc9RtFKqR3RjRqbdaU/R9j+xy340XdkR1WCvboQWaILzerQ/OaJK5pythUz0rjiZ4BkZdoVTT+a0z5VRHZ05HrSvr93tf8FW8PV+vwOyq8kqpKplA3g5lk3WvCnQi7m3049q4R26Wyt6ldHdluU1bsNBkVdFVT2j1fvhWbzVOT8fix+KVmx7TZDIFEFYLcugm4t0jgE54mRnaZXPU9csstM1Sin3itOkioA=
  - secure: pW7dgPJSM6tUrlRV4W9vT0MVbAM4q39xrELo3RoDYJU3dTzpHFWZyt0g9qBbCln3BlFg17KxQR/CFzLwA/VBrmwof/FbewYjlMxi5CquSrCzDf4RdX3ke7FzRsojYT1qiwJ4+1UhhUYS8h26EZjz8UJb/SxlaWNywaPaVVmigVIUcz3yz5SOz9p1hqm7xF6rJu4nGU5kieYqTqkTOcVVRb4AnQsCYfSHJlBsnUbWcqQZPmv0NXw+0SrjNYsFksaRLY2O6XxWfTpgvK79fVcO5PwcOfojKVi+wu/n3M2UsDNuHivucVbz9pTH5b3hoqSR5jk+pPoYyMdgT7tP+5RZLxXZiLbDm0E154JO3rfBUivgbHo+FOqGNsYGZjwk0xw/ZVN3N+/y4Z+ZjmufQb4YjcXOETWhnrq+CBWHQGLLoYixI7FzVu3MoqhOEb2XYSXFu/fJPIi+tAfcSPbKz2osO+gZJle0yBLJ3cGA/QT4gTPpse2OZ2PEl1NHQpXDzPV8IOQQ13K8AaDq+ifzoqU+3EtoI4lcGydXSqHrbZApW/+WZfJzx8O0cKS9gGZ/FSDL3JmFRWGpa/213qW+OEk+mk+j+GJfAcMv5kEiJ2boIDd5JNQEuIT+X1vyMgKPd35Q5yBwK1qe2aO/ZlOHCRfT6P+qAeDtOVNenhL737w2mEA=
  - secure: oNWa1K7EzRpf8zgdmAmfLx0jCU3aj4Nx5Jucks5Qwxi+mwcoVAguZqrm749fQnnT1AyP99Q87WsWcQ6L/Oe+zt1JW4SnHZELEbbN1LjxyC+evduipP4CR+qRoL9jLXavLCgRqQWi0PCZNHHBYlZBaFJ6bYFrTx3IVHETEci9WCe6Wu7wSFhAyOQ99CuMtOHivJhNURSxmLman1lQOgUU09SRni0lAJZHyK4wJf0U/I2eL13Ajxx1Sanog5BbVXAaWuP3nW2NOy3hSXEFPQdsMXGh1TJB4u2KmPWUWqMIm8COnGMm2fh2Z9E8YAGwaGlcfu9n3PRu/a8mUDkbqI2woSuj7bRKyULUsX2dyTvQJ9c8j4tkxPmYIi+xS6T3cc8BSs1fKj1ibtb+BcaVimwdBQuFehNX8d2o85zFIddxkwUx+1mMttqhs4FF5d+JU5XkzVdUqBT2H/sAzm8YA1/i8BGDik7xkGmj9pqUk2BZzOMAOpnGV+aKWyBlJ/LWHSHVMA2XeaLDbdVCBR1oMGj/JLm6Qd2ofa2/pG0FKxJHY3I8ifPoUkua5HbtFHmDB8G7+xz2eI4dSQAPVziHKJIpPb4lbqL30aso2x+I4HQ0DkEDx+x0ijVjRe6m4vFPco5K9AdOXWjIIG9PinyzunMgNFvjqQody8ZplcMO/JCt228=
before_install:
- openssl aes-256-cbc -K $encrypted_af02bb7c7f63_key -iv $encrypted_af02bb7c7f63_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar -xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
- echo $GCE_PROJECT_ID
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
notifications:
  slack:
    rooms:
      secure: qj4HA/A0JF6D/IH3cSc5iy0bNlVikAvlwilMDrJ4jy0yM/9XDk25HSo2MU0WGFU8xtNgW6Z7vy0ONdG8dXAWNLHO1nwKu0ae2h2VuEwJMrIVh1X9ii3apBQpvfz+OABT7sbUUZTqLq1emXn2TMuE7EsubrRqAqSEvGjXsSiocijknNd6YQ6q82/pl8ADHdMu76pfeEEg+iMFO6iSRdW5W42XoP1Yb6wu9TBCPnDqwDs7YByXkfMDn/t1S02y5TpyiPqebQvmdYtwWtGSFVyZwFTaeK5X+qi9Fe/S8vtS3X/B/+8yB9Mc+doLkN7TNXPaOkeCFjufcYWeRVzwcISUsJ7SKP/4oN5CZcFXx2QKRyoZl2EIUq9Q+X9PC6e1Z1bhbkHIr9OE59ycTdn4I3shllAjll4sP5kRl8vDrwp5H3l1hwggpZoMES7q1s1LZ4hzy7WynG5F3dQ5oyaAe2N/69yNROhYz8O25PI0uaQdD42F+xqaFn12LV6QMLGhwor9BdlagPCWlezSzBPfs15y6qdwlpKJvpetaLZ3bVRBm2OA2AYuIV8vpKFS0dLwpvVex0YvQxvDJe6RDFFCwFDt5yscZVpxqE4/cy0iv58m03JkEiSZlT2UW64KvnzHyXTk+aHoqFJgLV+fGd9TinUrEmkkAKx2f7pgDwZbAToL3U8=
