language: python
python:
- '3.6'
install:
- pip install ansible==2.7.1 molecule==2.19.0 apache-libcloud pycrypto
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/moonlit-watch-219508-3e24e1b38cc1.json"
  global:
  - secure: E2wNbTprc5n8jLVySCrITQLbibUwkyRYJGWu0Nk3nPkBFNsyvOqjAvlQl5Mj1joaQCvb1biPLyunNUlIDlGd0oTIL4isFMV8HrfhFieIi0EL+TgmS4XNlI0vDLEVLXjhnyx9CjE1f+aOcqBJZXZHU16De/M7hm436y9nrJurnGGXEzAwtD5I3YWywCUYM174LcILoTc+qJOze4iQQEmq3MfqdZTnJCjk4Fh5W7nn23nODwitMu4KN2qsWBzlvuzJn4fYJ1HA33/6C+VeriiHESoaT+sZcLXjhh4qEJNbt+WmCRJ7rIkL+I6r92JhWiKcXodxrUWF4LdLDmvskxXEqo30LSjgfu19itkLSmv5e7K2ed3CuR3zBeoTgBMjOk1NaZ54drxdsDtBNVjcTT0grbGEapV5qhtaGumifLiImnCSM22ZRH5bgL6zy0tTrK4K4hPX8Ib5ddLL5SonxL1jqN0JHmjwqwlWRvbmY6CRDKkk95XmXEgPGG1PC2qkIRV6vFT8RasDeW+kIFS7C7r+1MKeDlMEAhZFP99+1A5oO+1WUpkpMsWUg2XqF1/fqxqk/aJTSJATQY2uyaVoAVkDXjWIQjWVeq1ulY1xa1+fhOflDVqoXqqEcjBrvoqwMyAntA5P1fjVF6iF7BEkumJNTAo1kTLkh0B05mzfvtqsPuI=
  - secure: aCdw1+w/4JvCkyNVFEZmLY2QaDJHjjNpeGTwMOsNulTzO5EQ1ahMPbdiGMCNaOeptqKpIfsk8N+UDP66N6GemWwYEBk+iKNfUJQwZg/vWygLmzmSdP5DE5NMYSKktGF4qEkN1j2lsOcv8UHme3kPQ8vLjETONBghC74XmWUoTdjXQP54broyo5TpVSkk6HEG/pbyyD+zg5w4KZKaBxmDTenXPVDijtPGv9idupR4Y0CrUCUe/HgnBg88Hi0jLR/gCaWTAYHL1I5Kgl+PRoR+spHMaQfNGaS1lgzmeLwPPf06TSO50yt/8M+qz0FN8ot5PlWaPfBqG9pxU1knQKftBCv3E18f2oBkZ5ai+3I8ez3PKndDn74Ccyvdb4oIhEtYr7qLhcOga+vJLXJLEDSyght0HnQJ//m4e1iyTqr9mDynJ/yJ5TIWw4e03YTuM6n4+v8J39HaBn6kBail/YDPnwzmkpPh7zq9TxdWAJk8EkE6OJEg2SIBhNg9LfEHV0caATAA0beLm0iGzMde8yoO8h0ZQAloWQZGcPXAi1GEXUSQl9VwE96zy6T9p273V7GRIAgbOGHgbw/sO+KqgGRvCNUizz2OiFJtKQsXhCQWYvE0KBCprYAbtVGLb1de75GBSS2+AR6lBqKXa/e+Tx29+esuMBcJiAxRyqvsuot/BXs=
  - secure: b86Y5UTNyViFOsP44ZYi/vdKN9kgpHMl7ryP5jVw6fn4f1NqwLH3S7mQk9SzN0chGl75b4ZiwwQSTvqu+oqkNcKVBXbbk82/0RwleGY0Oyqeck02NYGunP8+dRC3N+kC2eC47TdRhy9eaUE5syuJ6IjglHR6nJhLaNzYojzkUNqCoMTELDN7NVZ56EwI7Hanr9hWbNFKf7WqYFv8oPyqM55jfCqAYItjh5moyF3QJQCYBd1tkVy8KnaZuj2cTU/TE6oCV2QuewQfX3dEgnhvLtMADH3Gs9RFZpYdpvkaEjs5bGcLCEQoIltGXTwTMDvdVttxW4n3JUoV+ftFXJqg+K86H2odVr12nYyeeGVqnj2f8tuEIjSF7nNINcLJqSR1KUrOtYzbZIaj8HrcG7faf6oiCW7nCOOPF9xrfaqJSk4biZRib8r14dNdE8KTMQuRSso4GAVYJHX+03qycZ+L56GzYbqUFduHE9SlhmfKGWc+CW8ZioceOr66oKKOEhV17lCQdH51Lp08iJFdCra92Vvq2GW/tDWOUL5aAQ+f2aHtdL5IWHMoHHEVjRGqbDbbOi9xE8S5sV2wnyTt3oOvMdPkIUaKzjbsviIEq+DaDySZPdXwwW3waZa6otGOVUiVT89RbTSVqiUYoyQHFnDkMD0C9dHDTVWVtKR+aPnarjU=
before_install:
- openssl aes-256-cbc -K $encrypted_af02bb7c7f63_key -iv $encrypted_af02bb7c7f63_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar -xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
- echo $GCE_PROJECT_ID
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
notifications:
  slack:
    rooms:
      secure: qj4HA/A0JF6D/IH3cSc5iy0bNlVikAvlwilMDrJ4jy0yM/9XDk25HSo2MU0WGFU8xtNgW6Z7vy0ONdG8dXAWNLHO1nwKu0ae2h2VuEwJMrIVh1X9ii3apBQpvfz+OABT7sbUUZTqLq1emXn2TMuE7EsubrRqAqSEvGjXsSiocijknNd6YQ6q82/pl8ADHdMu76pfeEEg+iMFO6iSRdW5W42XoP1Yb6wu9TBCPnDqwDs7YByXkfMDn/t1S02y5TpyiPqebQvmdYtwWtGSFVyZwFTaeK5X+qi9Fe/S8vtS3X/B/+8yB9Mc+doLkN7TNXPaOkeCFjufcYWeRVzwcISUsJ7SKP/4oN5CZcFXx2QKRyoZl2EIUq9Q+X9PC6e1Z1bhbkHIr9OE59ycTdn4I3shllAjll4sP5kRl8vDrwp5H3l1hwggpZoMES7q1s1LZ4hzy7WynG5F3dQ5oyaAe2N/69yNROhYz8O25PI0uaQdD42F+xqaFn12LV6QMLGhwor9BdlagPCWlezSzBPfs15y6qdwlpKJvpetaLZ3bVRBm2OA2AYuIV8vpKFS0dLwpvVex0YvQxvDJe6RDFFCwFDt5yscZVpxqE4/cy0iv58m03JkEiSZlT2UW64KvnzHyXTk+aHoqFJgLV+fGd9TinUrEmkkAKx2f7pgDwZbAToL3U8=
